// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DenaAPI.Models;

[Table("Intermediate")]
[Index("AttributeId", Name = "IX_Intermediate_AttributeId")]
[Index("ProductId", Name = "IX_Intermediate_ProductId")]
public partial class Intermediate
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int AttributeId { get; set; }

    public long Price { get; set; }

    [ForeignKey("AttributeId")]
    [InverseProperty("Intermediates")]
    public virtual Attribute Attribute { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Intermediates")]
    public virtual Product Product { get; set; }
}