// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DenaAPI.Models;

[Table("PostDetail")]
public partial class PostDetail
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string Recipientname { get; set; }

    [StringLength(50)]
    public string Phone { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(255)]
    public string Considreations { get; set; }

    [InverseProperty("Post")]
    public virtual ICollection<Factor> Factors { get; } = new List<Factor>();
}