// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DenaAPI.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int CatId { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<Factor> Factors { get; } = new List<Factor>();

    [InverseProperty("Product")]
    public virtual ICollection<Intermediate> Intermediates { get; } = new List<Intermediate>();
}