// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DenaAPI.Models;

[Table("Sms")]
public partial class Sms
{
    [Key]
    public int Id { get; set; }
    public int UserId { get; set; }

    [StringLength(15)]
    public string Phone { get; set; }

    public int SmsId { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime TS { get; set; }

    public virtual User User { get; set; }
}