// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DenaAPI.Models;

[Table("Verification")]
public partial class Verification
{
    [Key]
    public int Id { get; set; }

    [StringLength(15)]
    public string Phone { get; set; }

    public int? VerificationId { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? TS { get; set; }

    public int? UserId { get; set; }
}